id: I40AD9137
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-05-30T22:17:17.087335'
last_modified: '2022-05-30T22:17:17.087341'
parser: null
source_metadata:
  title: Khenpo Pema Vajra Series
  language: zh
  description: Texts by and about the Dzogchen scholar Khenpo Pema Vajra (padma badzra,
    c. 1807–1884), also known as Khenpo Pema Dorje.
  volume:
    f3480:
      title: A Liberating Reminder
      base_file: f3480.txt
      order: 1
      parent: Advice
    f1129:
      title: The Life of Khenpo Pema Vajra
      base_file: f1129.txt
      order: 2
      parent: Biography
    f7C2C:
      title: A Brief Overview of the Three Turnings and the Mantra Piṭaka of the Vidyādharas
      base_file: f7C2C.txt
      order: 3
      parent: Commentaries
    fB567:
      title: 'Ornament of the Vidyādharas’ Wisdom: A Recitation Manual for the Great
        Compassionate One, Natural Liberation of Suffering (Dukngal Rangdrol)'
      base_file: fB567.txt
      order: 4
      parent: Commentaries
    fC5CC:
      title: 'Words from the Lineage Masters to Clarify Maitreyanātha''s Vision: An
        Overview of the Perfection of Wisdom''s Ornament of Realization'
      base_file: fC5CC.txt
      order: 5
      parent: Commentaries
    f9622:
      title: A Clear and Concise Description of the Practice of Śamatha
      base_file: f9622.txt
      order: 6
      parent: Meditation
    fA9F0:
      title: Brief Light Offering Prayer
      base_file: fA9F0.txt
      order: 7
      parent: Prayers
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
